import {
  SchoolTenant,
  SubscriptionPlan,
  PaymentTransaction,
  GlobalUser,
  SupportTicket,
  SuperAdminTeamMember,
  AuditLog,
  SystemServiceStatus,
  SystemIncident,
  GlobalAnnouncement,
  SuperAdminSettingsState
} from './types';

export const initialSuperAdminPlans: SubscriptionPlan[] = [
  {
    id: 'plan-starter',
    name: 'Starter',
    tagline: 'Ideal for single-campus academies and primary schools',
    monthlyPricePKR: 18500,
    annualPricePKR: 195000,
    maxStudents: 350,
    maxTeachers: 25,
    maxStaff: 10,
    storageGB: 50,
    maxCourses: 30,
    features: [
      'Student & Teacher Information System',
      'Daily Attendance with SMS Alerts',
      'Basic Fee Management (PKR Receipts)',
      'Examination & Grading (Percentage)',
      'Parent Portal Mobile Web',
      'Email Support'
    ],
    supportLevel: 'Standard (Email)',
    trialPeriodDays: 14,
    status: 'Active',
    subscriberCount: 312,
    isPopular: false
  },
  {
    id: 'plan-professional',
    name: 'Professional',
    tagline: 'Complete digital management for growing schools & colleges',
    monthlyPricePKR: 45000,
    annualPricePKR: 480000,
    maxStudents: 1200,
    maxTeachers: 85,
    maxStaff: 30,
    storageGB: 250,
    maxCourses: 150,
    features: [
      'Everything in Starter',
      'Automated Online Fee Collection (JazzCash / 1Link)',
      'Full LMS with Video Modules & Assignments',
      'Cambridge (O/A Level) & Board GPA Systems',
      'Automated WhatsApp Attendance & Fee Notices',
      'Live Timetable Generator',
      'Priority Phone & WhatsApp Support'
    ],
    supportLevel: 'Priority (Phone & WhatsApp)',
    trialPeriodDays: 21,
    status: 'Active',
    subscriberCount: 684,
    isPopular: true
  },
  {
    id: 'plan-enterprise',
    name: 'Enterprise',
    tagline: 'High-scale multi-wing colleges and elite school chains',
    monthlyPricePKR: 95000,
    annualPricePKR: 1020000,
    maxStudents: 5000,
    maxTeachers: 300,
    maxStaff: 100,
    storageGB: 1000,
    maxCourses: 600,
    features: [
      'Everything in Professional',
      'Multi-Wing & Multi-Campus Management',
      'Direct Banking Integration (HBL / Meezan / Raast)',
      'Custom Domain & Branded Mobile Web Portal',
      'Advanced Biometric Attendance Sync API',
      'Dedicated Account Manager & 99.99% SLA',
      'Custom Board Report Cards & Transcripts'
    ],
    supportLevel: '24/7 Dedicated SLA',
    trialPeriodDays: 30,
    status: 'Active',
    subscriberCount: 268,
    isPopular: false
  },
  {
    id: 'plan-custom',
    name: 'Custom Campus',
    tagline: 'Tailored enterprise licensing for nationwide education networks',
    monthlyPricePKR: 175000,
    annualPricePKR: 1900000,
    maxStudents: 20000,
    maxTeachers: 1200,
    maxStaff: 500,
    storageGB: 5000,
    maxCourses: 2500,
    features: [
      'Unlimited Campus Hierarchy',
      'On-Premise or Private Cloud Deployment Option',
      'Custom ERP & HR Payroll Module Integration',
      'Custom Security Audits & SLA Guarantee',
      'Dedicated Solution Architect'
    ],
    supportLevel: 'Dedicated Account Manager',
    trialPeriodDays: 30,
    status: 'Active',
    subscriberCount: 20,
    isPopular: false
  }
];

export const initialSchoolTenants: SchoolTenant[] = [
  {
    id: 'sch-001',
    code: 'BSS-LHE-01',
    name: 'Beaconhouse School System (Main Campus)',
    logo: 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=120&auto=format&fit=crop&q=80',
    type: 'Private School',
    address: '10-A, Block C, Gulberg III',
    city: 'Lahore',
    province: 'Punjab',
    phone: '+92 42 35789123',
    email: 'admissions@bss.edu.pk',
    website: 'https://beaconhouse.edu.pk',
    principalName: 'Dr. Tariq Mahmood Malik',
    principalEmail: 'principal.gulberg@bss.edu.pk',
    principalPhone: '+92 300 8456123',
    planId: 'plan-enterprise',
    planName: 'Enterprise',
    billingCycle: 'annual',
    status: 'Active',
    studentCount: 2450,
    maxStudents: 5000,
    teacherCount: 165,
    maxTeachers: 300,
    staffCount: 42,
    parentCount: 2180,
    coursesCount: 210,
    maxCourses: 600,
    storageUsedGB: 412.5,
    storageLimitGB: 1000,
    monthlyFeePKR: 95000,
    annualFeePKR: 1020000,
    nextBillingDate: '2026-11-15',
    createdDate: '2023-04-10',
    lastActive: '3 minutes ago',
    academicSystem: 'Cambridge (O/A Levels)',
    gradingSystem: 'Cambridge (A*-U)',
    timezone: 'Asia/Karachi',
    currency: 'PKR'
  },
  {
    id: 'sch-002',
    code: 'TCS-ISB-04',
    name: 'The City School (Capital Campus)',
    logo: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=120&auto=format&fit=crop&q=80',
    type: 'Private School',
    address: 'Plot 12, Sector H-8/1, Islamabad',
    city: 'Islamabad',
    province: 'Islamabad Capital Territory',
    phone: '+92 51 4862300',
    email: 'admin.isb@tcs.edu.pk',
    website: 'https://thecityschool.edu.pk',
    principalName: 'Mrs. Farhana Rasheed',
    principalEmail: 'f.rasheed@tcs.edu.pk',
    principalPhone: '+92 321 5567890',
    planId: 'plan-enterprise',
    planName: 'Enterprise',
    billingCycle: 'monthly',
    status: 'Active',
    studentCount: 1890,
    maxStudents: 5000,
    teacherCount: 130,
    maxTeachers: 300,
    staffCount: 35,
    parentCount: 1720,
    coursesCount: 180,
    maxCourses: 600,
    storageUsedGB: 340.2,
    storageLimitGB: 1000,
    monthlyFeePKR: 95000,
    annualFeePKR: 1020000,
    nextBillingDate: '2026-09-01',
    createdDate: '2023-08-15',
    lastActive: 'Just now',
    academicSystem: 'Cambridge (O/A Levels)',
    gradingSystem: 'Cambridge (A*-U)',
    timezone: 'Asia/Karachi',
    currency: 'PKR'
  },
  {
    id: 'sch-003',
    code: 'APS-PSH-02',
    name: 'Army Public School & College (Peshawar)',
    logo: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=120&auto=format&fit=crop&q=80',
    type: 'Cadet College',
    address: 'Warsak Road, Peshawar Cantt',
    city: 'Peshawar',
    province: 'Khyber Pakhtunkhwa',
    phone: '+92 91 5841022',
    email: 'info@apsacs.edu.pk',
    principalName: 'Brig. (R) Asim Jahangir',
    principalEmail: 'principal.psh@apsacs.edu.pk',
    principalPhone: '+92 333 9123456',
    planId: 'plan-enterprise',
    planName: 'Enterprise',
    billingCycle: 'annual',
    status: 'Active',
    studentCount: 3100,
    maxStudents: 5000,
    teacherCount: 195,
    maxTeachers: 300,
    staffCount: 60,
    parentCount: 2850,
    coursesCount: 310,
    maxCourses: 600,
    storageUsedGB: 680.0,
    storageLimitGB: 1000,
    monthlyFeePKR: 95000,
    annualFeePKR: 1020000,
    nextBillingDate: '2027-01-20',
    createdDate: '2023-01-12',
    lastActive: '12 minutes ago',
    academicSystem: 'Federal Board (FBISE)',
    gradingSystem: 'Percentage (Board)',
    timezone: 'Asia/Karachi',
    currency: 'PKR'
  },
  {
    id: 'sch-004',
    code: 'KGS-KHI-01',
    name: 'Karachi Grammar School (Clifton Campus)',
    logo: 'https://images.unsplash.com/photo-1562774053-701939374585?w=120&auto=format&fit=crop&q=80',
    type: 'Private School',
    address: 'Block 5, Clifton, Karachi',
    city: 'Karachi',
    province: 'Sindh',
    phone: '+92 21 35871144',
    email: 'info@kgs.edu.pk',
    principalName: 'Dr. Michael D\'Souza',
    principalEmail: 'principal@kgs.edu.pk',
    principalPhone: '+92 300 2198765',
    planId: 'plan-enterprise',
    planName: 'Enterprise',
    billingCycle: 'annual',
    status: 'Active',
    studentCount: 2200,
    maxStudents: 5000,
    teacherCount: 155,
    maxTeachers: 300,
    staffCount: 45,
    parentCount: 1980,
    coursesCount: 240,
    maxCourses: 600,
    storageUsedGB: 520.4,
    storageLimitGB: 1000,
    monthlyFeePKR: 95000,
    annualFeePKR: 1020000,
    nextBillingDate: '2026-10-05',
    createdDate: '2023-06-22',
    lastActive: '5 minutes ago',
    academicSystem: 'Cambridge (O/A Levels)',
    gradingSystem: 'Cambridge (A*-U)',
    timezone: 'Asia/Karachi',
    currency: 'PKR'
  },
  {
    id: 'sch-005',
    code: 'RMC-RWP-01',
    name: 'Roots Millennium Colleges (Kingsbury Campus)',
    logo: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=120&auto=format&fit=crop&q=80',
    type: 'College',
    address: 'Sector F-8/4, Rawalpindi / Islamabad',
    city: 'Rawalpindi',
    province: 'Punjab',
    phone: '+92 51 2854000',
    email: 'admissions@millenniumschools.edu.pk',
    principalName: 'Mrs. Sabahat Rizvi',
    principalEmail: 'sabahat.r@millenniumschools.edu.pk',
    principalPhone: '+92 322 5147890',
    planId: 'plan-professional',
    planName: 'Professional',
    billingCycle: 'monthly',
    status: 'Active',
    studentCount: 890,
    maxStudents: 1200,
    teacherCount: 64,
    maxTeachers: 85,
    staffCount: 20,
    parentCount: 810,
    coursesCount: 92,
    maxCourses: 150,
    storageUsedGB: 142.8,
    storageLimitGB: 250,
    monthlyFeePKR: 45000,
    annualFeePKR: 480000,
    nextBillingDate: '2026-08-25',
    createdDate: '2024-02-14',
    lastActive: '18 minutes ago',
    academicSystem: 'Cambridge (O/A Levels)',
    gradingSystem: 'GPA 4.0',
    timezone: 'Asia/Karachi',
    currency: 'PKR'
  },
  {
    id: 'sch-006',
    code: 'DPS-FSD-01',
    name: 'Divisional Public School & College (Faisalabad)',
    logo: 'https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=120&auto=format&fit=crop&q=80',
    type: 'Higher Secondary',
    address: 'Jail Road, Civil Lines',
    city: 'Faisalabad',
    province: 'Punjab',
    phone: '+92 41 9200155',
    email: 'dpsfsd@gov.pk',
    principalName: 'Prof. Muhammad Akram Gondal',
    principalEmail: 'principal@dpsfsd.edu.pk',
    principalPhone: '+92 300 6654321',
    planId: 'plan-professional',
    planName: 'Professional',
    billingCycle: 'annual',
    status: 'Active',
    studentCount: 1150,
    maxStudents: 1200,
    teacherCount: 78,
    maxTeachers: 85,
    staffCount: 28,
    parentCount: 1040,
    coursesCount: 130,
    maxCourses: 150,
    storageUsedGB: 198.0,
    storageLimitGB: 250,
    monthlyFeePKR: 45000,
    annualFeePKR: 480000,
    nextBillingDate: '2026-12-10',
    createdDate: '2024-01-05',
    lastActive: '1 hour ago',
    academicSystem: 'National Matric / FSc',
    gradingSystem: 'Percentage (Board)',
    timezone: 'Asia/Karachi',
    currency: 'PKR'
  },
  {
    id: 'sch-007',
    code: 'PGC-GRW-03',
    name: 'Punjab Group of Colleges (Campus 2 Gujranwala)',
    logo: 'https://images.unsplash.com/photo-1519452635265-7b1fbfd1e4e0?w=120&auto=format&fit=crop&q=80',
    type: 'College',
    address: 'Sialkot Bypass Road, Gujranwala',
    city: 'Gujranwala',
    province: 'Punjab',
    phone: '+92 55 3892400',
    email: 'pgc.grw@pgc.edu',
    principalName: 'Prof. Naveed Aslam',
    principalEmail: 'naveed.aslam@pgc.edu',
    principalPhone: '+92 301 8765432',
    planId: 'plan-professional',
    planName: 'Professional',
    billingCycle: 'monthly',
    status: 'Active',
    studentCount: 980,
    maxStudents: 1200,
    teacherCount: 68,
    maxTeachers: 85,
    staffCount: 22,
    parentCount: 920,
    coursesCount: 110,
    maxCourses: 150,
    storageUsedGB: 165.2,
    storageLimitGB: 250,
    monthlyFeePKR: 45000,
    annualFeePKR: 480000,
    nextBillingDate: '2026-08-28',
    createdDate: '2024-03-01',
    lastActive: '35 minutes ago',
    academicSystem: 'National Matric / FSc',
    gradingSystem: 'Percentage (Board)',
    timezone: 'Asia/Karachi',
    currency: 'PKR'
  },
  {
    id: 'sch-008',
    code: 'BHS-MLT-01',
    name: 'Bloomfield Hall School (Multan Cantt)',
    logo: 'https://images.unsplash.com/photo-1546410531-bb4caa6b424d?w=120&auto=format&fit=crop&q=80',
    type: 'Private School',
    address: 'Old Bahawalpur Road, Multan',
    city: 'Multan',
    province: 'Punjab',
    phone: '+92 61 4512990',
    email: 'bhs.multan@bhs.edu.pk',
    principalName: 'Mrs. Shahida Qureshi',
    principalEmail: 's.qureshi@bhs.edu.pk',
    principalPhone: '+92 302 7654321',
    planId: 'plan-starter',
    planName: 'Starter',
    billingCycle: 'monthly',
    status: 'Active',
    studentCount: 310,
    maxStudents: 350,
    teacherCount: 22,
    maxTeachers: 25,
    staffCount: 8,
    parentCount: 290,
    coursesCount: 26,
    maxCourses: 30,
    storageUsedGB: 34.5,
    storageLimitGB: 50,
    monthlyFeePKR: 18500,
    annualFeePKR: 195000,
    nextBillingDate: '2026-09-05',
    createdDate: '2024-05-18',
    lastActive: '2 hours ago',
    academicSystem: 'Cambridge (O/A Levels)',
    gradingSystem: 'Cambridge (A*-U)',
    timezone: 'Asia/Karachi',
    currency: 'PKR'
  },
  {
    id: 'sch-009',
    code: 'QMA-QTA-01',
    name: 'Quetta Model Academy & College',
    logo: 'https://images.unsplash.com/photo-1564981797816-1043664bf78d?w=120&auto=format&fit=crop&q=80',
    type: 'O/A Levels Academy',
    address: 'Zarghoon Road, Quetta',
    city: 'Quetta',
    province: 'Balochistan',
    phone: '+92 81 2824110',
    email: 'contact@quettaacademy.edu.pk',
    principalName: 'Mirza Jahangir Khan',
    principalEmail: 'jahangir.khan@quettaacademy.edu.pk',
    principalPhone: '+92 334 8123456',
    planId: 'plan-starter',
    planName: 'Starter',
    billingCycle: 'monthly',
    status: 'Trial',
    studentCount: 180,
    maxStudents: 350,
    teacherCount: 16,
    maxTeachers: 25,
    staffCount: 5,
    parentCount: 165,
    coursesCount: 18,
    maxCourses: 30,
    storageUsedGB: 12.4,
    storageLimitGB: 50,
    monthlyFeePKR: 18500,
    annualFeePKR: 195000,
    nextBillingDate: '2026-08-22',
    trialEndsAt: '2026-08-22',
    createdDate: '2026-08-08',
    lastActive: '45 minutes ago',
    academicSystem: 'Federal Board (FBISE)',
    gradingSystem: 'Percentage (Board)',
    timezone: 'Asia/Karachi',
    currency: 'PKR'
  },
  {
    id: 'sch-010',
    code: 'FLS-HYD-02',
    name: 'Future Leaders Grammar School (Hyderabad)',
    logo: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=120&auto=format&fit=crop&q=80',
    type: 'Private School',
    address: 'Auto Bhan Road, Latifabad',
    city: 'Hyderabad',
    province: 'Sindh',
    phone: '+92 22 3810234',
    email: 'admin@fls-hyd.edu.pk',
    principalName: 'Ms. Rubina Memon',
    principalEmail: 'rubina.m@fls-hyd.edu.pk',
    principalPhone: '+92 312 3456789',
    planId: 'plan-starter',
    planName: 'Starter',
    billingCycle: 'monthly',
    status: 'Pending',
    studentCount: 220,
    maxStudents: 350,
    teacherCount: 18,
    maxTeachers: 25,
    staffCount: 6,
    parentCount: 195,
    coursesCount: 15,
    maxCourses: 30,
    storageUsedGB: 8.5,
    storageLimitGB: 50,
    monthlyFeePKR: 18500,
    annualFeePKR: 195000,
    nextBillingDate: '2026-08-30',
    createdDate: '2026-08-11',
    lastActive: '5 hours ago',
    academicSystem: 'National Matric / FSc',
    gradingSystem: 'Percentage (Board)',
    timezone: 'Asia/Karachi',
    currency: 'PKR'
  },
  {
    id: 'sch-011',
    code: 'CMS-LHE-05',
    name: 'Crescent Model Higher Secondary School',
    logo: 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=120&auto=format&fit=crop&q=80',
    type: 'Higher Secondary',
    address: 'Shadman Colony, Lahore',
    city: 'Lahore',
    province: 'Punjab',
    phone: '+92 42 37582299',
    email: 'accounts@crescentschool.edu.pk',
    principalName: 'Hafiz Muhammad Bilal',
    principalEmail: 'principal@crescentschool.edu.pk',
    principalPhone: '+92 300 4123890',
    planId: 'plan-professional',
    planName: 'Professional',
    billingCycle: 'monthly',
    status: 'Suspended',
    studentCount: 750,
    maxStudents: 1200,
    teacherCount: 52,
    maxTeachers: 85,
    staffCount: 18,
    parentCount: 690,
    coursesCount: 80,
    maxCourses: 150,
    storageUsedGB: 110.0,
    storageLimitGB: 250,
    monthlyFeePKR: 45000,
    annualFeePKR: 480000,
    nextBillingDate: '2026-07-15',
    createdDate: '2023-11-20',
    lastActive: '3 days ago',
    academicSystem: 'National Matric / FSc',
    gradingSystem: 'Percentage (Board)',
    timezone: 'Asia/Karachi',
    currency: 'PKR'
  },
  {
    id: 'sch-012',
    code: 'CCH-ATT-01',
    name: 'Cadet College Hasanabdal',
    logo: 'https://images.unsplash.com/photo-1577495508048-b635879837f1?w=120&auto=format&fit=crop&q=80',
    type: 'Cadet College',
    address: 'G.T. Road, Hasanabdal, District Attock',
    city: 'Attock',
    province: 'Punjab',
    phone: '+92 57 2520200',
    email: 'cch@cch.edu.pk',
    website: 'https://cch.edu.pk',
    principalName: 'Brig. (R) Nasir Saeed Khattak',
    principalEmail: 'principal@cch.edu.pk',
    principalPhone: '+92 333 5551122',
    planId: 'plan-custom',
    planName: 'Custom Campus',
    billingCycle: 'annual',
    status: 'Active',
    studentCount: 1650,
    maxStudents: 20000,
    teacherCount: 110,
    maxTeachers: 1200,
    staffCount: 40,
    parentCount: 1580,
    coursesCount: 160,
    maxCourses: 2500,
    storageUsedGB: 480.0,
    storageLimitGB: 5000,
    monthlyFeePKR: 175000,
    annualFeePKR: 1900000,
    nextBillingDate: '2027-03-01',
    createdDate: '2022-09-01',
    lastActive: '8 minutes ago',
    academicSystem: 'Federal Board (FBISE)',
    gradingSystem: 'Percentage (Board)',
    timezone: 'Asia/Karachi',
    currency: 'PKR'
  }
];

export const initialPaymentTransactions: PaymentTransaction[] = [
  {
    id: 'tx-10982',
    transactionRef: 'TXN-PK-2026-8841',
    schoolId: 'sch-001',
    schoolName: 'Beaconhouse School System (Main Campus)',
    invoiceNo: 'INV-SaaS-2026-0941',
    amountPKR: 1020000,
    taxPKR: 0,
    discountPKR: 50000,
    netAmountPKR: 970000,
    currency: 'PKR',
    paymentMethod: 'Bank Transfer (Meezan/HBL)',
    status: 'Paid',
    date: '2026-08-10',
    paidAt: '2026-08-10 11:24 PKT',
    gatewayRef: 'MEEZAN-FT-994821',
    notes: 'Annual Enterprise Plan Renewal (Bank Transfer verified by Finance Team)'
  },
  {
    id: 'tx-10981',
    transactionRef: 'TXN-PK-2026-8840',
    schoolId: 'sch-002',
    schoolName: 'The City School (Capital Campus)',
    invoiceNo: 'INV-SaaS-2026-0940',
    amountPKR: 95000,
    taxPKR: 0,
    discountPKR: 0,
    netAmountPKR: 95000,
    currency: 'PKR',
    paymentMethod: '1Link 1Bill',
    status: 'Paid',
    date: '2026-08-01',
    paidAt: '2026-08-01 09:15 PKT',
    gatewayRef: '1BILL-09848123',
    notes: 'Monthly Enterprise subscription fee via 1Bill invoice'
  },
  {
    id: 'tx-10980',
    transactionRef: 'TXN-PK-2026-8839',
    schoolId: 'sch-005',
    schoolName: 'Roots Millennium Colleges (Kingsbury Campus)',
    invoiceNo: 'INV-SaaS-2026-0939',
    amountPKR: 45000,
    taxPKR: 0,
    discountPKR: 0,
    netAmountPKR: 45000,
    currency: 'PKR',
    paymentMethod: 'JazzCash',
    status: 'Paid',
    date: '2026-07-25',
    paidAt: '2026-07-25 14:02 PKT',
    gatewayRef: 'JC-MW-8831920',
    notes: 'Monthly Professional Plan payment via JazzCash Merchant Gateway'
  },
  {
    id: 'tx-10979',
    transactionRef: 'TXN-PK-2026-8838',
    schoolId: 'sch-007',
    schoolName: 'Punjab Group of Colleges (Campus 2 Gujranwala)',
    invoiceNo: 'INV-SaaS-2026-0938',
    amountPKR: 45000,
    taxPKR: 0,
    discountPKR: 0,
    netAmountPKR: 45000,
    currency: 'PKR',
    paymentMethod: 'EasyPaisa',
    status: 'Paid',
    date: '2026-07-28',
    paidAt: '2026-07-28 16:44 PKT',
    gatewayRef: 'EP-QR-449102',
    notes: 'EasyPaisa Direct settlement'
  },
  {
    id: 'tx-10978',
    transactionRef: 'TXN-PK-2026-8837',
    schoolId: 'sch-011',
    schoolName: 'Crescent Model Higher Secondary School',
    invoiceNo: 'INV-SaaS-2026-0937',
    amountPKR: 45000,
    taxPKR: 0,
    discountPKR: 0,
    netAmountPKR: 45000,
    currency: 'PKR',
    paymentMethod: '1Link 1Bill',
    status: 'Failed',
    date: '2026-07-15',
    gatewayRef: '1BILL-FAIL-TIMEOUT',
    failureReason: 'Account balance insufficient on invoice settlement attempt #3',
    notes: 'Auto-retry failed. School was placed in Suspended status pending clearance.'
  },
  {
    id: 'tx-10977',
    transactionRef: 'TXN-PK-2026-8836',
    schoolId: 'sch-008',
    schoolName: 'Bloomfield Hall School (Multan Cantt)',
    invoiceNo: 'INV-SaaS-2026-0936',
    amountPKR: 18500,
    taxPKR: 0,
    discountPKR: 0,
    netAmountPKR: 18500,
    currency: 'PKR',
    paymentMethod: 'Raast',
    status: 'Paid',
    date: '2026-08-05',
    paidAt: '2026-08-05 10:11 PKT',
    gatewayRef: 'RAAST-SBP-889102',
    notes: 'Instant Raast P2M settlement'
  },
  {
    id: 'tx-10976',
    transactionRef: 'TXN-PK-2026-8835',
    schoolId: 'sch-006',
    schoolName: 'Divisional Public School & College (Faisalabad)',
    invoiceNo: 'INV-SaaS-2026-0935',
    amountPKR: 480000,
    taxPKR: 0,
    discountPKR: 30000,
    netAmountPKR: 450000,
    currency: 'PKR',
    paymentMethod: 'Bank Transfer (Meezan/HBL)',
    status: 'Paid',
    date: '2025-12-10',
    paidAt: '2025-12-10 13:30 PKT',
    gatewayRef: 'HBL-CORP-449102',
    notes: 'Annual upfront subscription payment with 1-month promo discount'
  },
  {
    id: 'tx-10975',
    transactionRef: 'TXN-PK-2026-8834',
    schoolId: 'sch-010',
    schoolName: 'Future Leaders Grammar School (Hyderabad)',
    invoiceNo: 'INV-SaaS-2026-0934',
    amountPKR: 18500,
    taxPKR: 0,
    discountPKR: 0,
    netAmountPKR: 18500,
    currency: 'PKR',
    paymentMethod: 'JazzCash',
    status: 'Pending',
    date: '2026-08-11',
    gatewayRef: 'JC-PENDING-OTP',
    notes: 'Awaiting primary authorization from school accountant'
  },
  {
    id: 'tx-10974',
    transactionRef: 'TXN-PK-2026-8833',
    schoolId: 'sch-005',
    schoolName: 'Roots Millennium Colleges (Kingsbury Campus)',
    invoiceNo: 'INV-SaaS-2026-0899',
    amountPKR: 15000,
    taxPKR: 0,
    discountPKR: 0,
    netAmountPKR: 15000,
    currency: 'PKR',
    paymentMethod: 'Bank Transfer (Meezan/HBL)',
    status: 'Refunded',
    date: '2026-06-18',
    gatewayRef: 'REF-HBL-99120',
    notes: 'Partial billing adjustment refunded due to mid-cycle tier downgrade credit'
  }
];

export const initialGlobalUsers: GlobalUser[] = [
  {
    id: 'usr-sa-01',
    name: 'Syed Hamza Ali',
    email: 'hamza.ali@taleemlms.com.pk',
    phone: '+92 300 8594120',
    role: 'Super Admin',
    schoolName: 'TaleemLM SaaS Headquarters (Pakistan)',
    status: 'Active',
    lastActive: 'Just now',
    createdDate: '2022-01-01',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
    cnic: '35202-8491023-1'
  },
  {
    id: 'usr-pr-01',
    name: 'Dr. Tariq Mahmood Malik',
    email: 'principal.gulberg@bss.edu.pk',
    phone: '+92 300 8456123',
    role: 'Principal',
    schoolId: 'sch-001',
    schoolName: 'Beaconhouse School System (Main Campus)',
    status: 'Active',
    lastActive: '3 minutes ago',
    createdDate: '2023-04-10',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
    cnic: '35201-1928374-1'
  },
  {
    id: 'usr-pr-02',
    name: 'Mrs. Farhana Rasheed',
    email: 'f.rasheed@tcs.edu.pk',
    phone: '+92 321 5567890',
    role: 'Principal',
    schoolId: 'sch-002',
    schoolName: 'The City School (Capital Campus)',
    status: 'Active',
    lastActive: 'Just now',
    createdDate: '2023-08-15',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=120&auto=format&fit=crop&q=80',
    cnic: '61101-9988776-2'
  },
  {
    id: 'usr-tc-01',
    name: 'Sir Ahsan Farooq',
    email: 'ahsan.farooq@bss.edu.pk',
    phone: '+92 333 4519201',
    role: 'Teacher',
    schoolId: 'sch-001',
    schoolName: 'Beaconhouse School System (Main Campus)',
    status: 'Active',
    lastActive: '25 minutes ago',
    createdDate: '2023-05-01',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80',
    cnic: '35202-4455667-1'
  },
  {
    id: 'usr-tc-02',
    name: 'Ms. Ayesha Siddiqa',
    email: 'ayesha.s@tcs.edu.pk',
    phone: '+92 312 9845123',
    role: 'Teacher',
    schoolId: 'sch-002',
    schoolName: 'The City School (Capital Campus)',
    status: 'Active',
    lastActive: '1 hour ago',
    createdDate: '2023-09-10',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=120&auto=format&fit=crop&q=80',
    cnic: '61101-3322114-4'
  },
  {
    id: 'usr-st-01',
    name: 'Muhammad Saad Khan',
    email: 'saad.khan@students.bss.edu.pk',
    phone: '+92 345 8891024',
    role: 'Student',
    schoolId: 'sch-001',
    schoolName: 'Beaconhouse School System (Main Campus)',
    status: 'Active',
    lastActive: '12 minutes ago',
    createdDate: '2024-08-01',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=120&auto=format&fit=crop&q=80',
    cnic: '35201-9988112-9'
  },
  {
    id: 'usr-pt-01',
    name: 'Tariq Jameel Khan (Guardian)',
    email: 'tj.khan@gmail.com',
    phone: '+92 300 4455881',
    role: 'Parent',
    schoolId: 'sch-001',
    schoolName: 'Beaconhouse School System (Main Campus)',
    status: 'Active',
    lastActive: '4 hours ago',
    createdDate: '2024-08-01',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=120&auto=format&fit=crop&q=80',
    cnic: '35201-4455221-3'
  },
  {
    id: 'usr-ac-01',
    name: 'Rana Zulfiqar (Accountant)',
    email: 'accounts@apsacs.edu.pk',
    phone: '+92 333 9191020',
    role: 'Accountant',
    schoolId: 'sch-003',
    schoolName: 'Army Public School & College (Peshawar)',
    status: 'Active',
    lastActive: '40 minutes ago',
    createdDate: '2023-01-20',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=120&auto=format&fit=crop&q=80',
    cnic: '17301-8899221-1'
  }
];

export const initialSupportTickets: SupportTicket[] = [
  {
    id: 'tkt-401',
    ticketNumber: 'TKT-PK-9821',
    schoolId: 'sch-002',
    schoolName: 'The City School (Capital Campus)',
    subject: '1Link 1Bill automated reconciliation batch query',
    priority: 'High',
    category: 'Billing',
    assignedAgent: {
      id: 'tm-02',
      name: 'Zainab Fatima',
      avatar: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=120&auto=format&fit=crop&q=80',
      email: 'zainab.f@taleemlms.com.pk'
    },
    status: 'In Progress',
    createdDate: '2026-08-13 14:20',
    updatedDate: '2026-08-14 09:10',
    messages: [
      {
        id: 'msg-1',
        sender: 'Mrs. Farhana Rasheed',
        role: 'School Principal',
        avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=120&auto=format&fit=crop&q=80',
        text: 'Assalam-o-Alaikum team. Our finance officer noticed 14 fee payments processed on August 12 through HBL Mobile App via 1Bill are showing as Paid on the bank statement, but their receipt sync took 2 hours on the LMS dashboard. Could you check if 1Link webhook retry delay was triggered?',
        timestamp: '2026-08-13 14:20'
      },
      {
        id: 'msg-2',
        sender: 'Zainab Fatima',
        role: 'Support Agent',
        avatar: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=120&auto=format&fit=crop&q=80',
        text: 'Walaikum Assalam Mrs. Farhana. We checked our 1Link API gateway logs for the 12th. SBP (State Bank of Pakistan) 1Link settlement server had scheduled 15-minute maintenance which caused queuing. All 14 transactions have successfully settled with receipts generated and parents notified via SMS.',
        timestamp: '2026-08-14 09:10'
      }
    ],
    internalNotes: [
      {
        id: 'note-1',
        author: 'Zainab Fatima (Support)',
        text: 'Checked 1Link logs: response code 200 received after queue replay. No tenant data corrupted.',
        date: '2026-08-14 09:05'
      }
    ]
  },
  {
    id: 'tkt-402',
    ticketNumber: 'TKT-PK-9820',
    schoolId: 'sch-003',
    schoolName: 'Army Public School & College (Peshawar)',
    subject: 'FBISE Board Grade 9 & 10 Model Paper assessment format',
    priority: 'Medium',
    category: 'Academics & LMS',
    assignedAgent: {
      id: 'tm-03',
      name: 'Bilal Hassan Qureshi',
      avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=120&auto=format&fit=crop&q=80',
      email: 'bilal.q@taleemlms.com.pk'
    },
    status: 'Waiting for Customer',
    createdDate: '2026-08-12 10:15',
    updatedDate: '2026-08-13 11:30',
    messages: [
      {
        id: 'msg-1',
        sender: 'Brig. (R) Asim Jahangir',
        role: 'School Principal',
        avatar: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=120&auto=format&fit=crop&q=80',
        text: 'We are setting up First Term Examination for Class 9 Federal Board. We need SLO-based (Student Learning Outcomes) question categorization rubric added into the question bank module.',
        timestamp: '2026-08-12 10:15'
      },
      {
        id: 'msg-2',
        sender: 'Bilal Hassan Qureshi',
        role: 'Support Agent',
        avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=120&auto=format&fit=crop&q=80',
        text: 'Dear Principal Sahib, we have enabled the FBISE SLO Rubrics template on your campus portal under Assessment Settings -> Grading Standards. Please review and confirm if it meets your exam committee requirements.',
        timestamp: '2026-08-13 11:30'
      }
    ],
    internalNotes: []
  },
  {
    id: 'tkt-403',
    ticketNumber: 'TKT-PK-9819',
    schoolId: 'sch-009',
    schoolName: 'Quetta Model Academy & College',
    subject: 'Request for 14-day trial extension for Board approval',
    priority: 'Low',
    category: 'Billing',
    assignedAgent: {
      id: 'tm-04',
      name: 'Omer Farooq (Sales Lead)',
      avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=120&auto=format&fit=crop&q=80',
      email: 'omer.f@taleemlms.com.pk'
    },
    status: 'Open',
    createdDate: '2026-08-14 08:00',
    updatedDate: '2026-08-14 08:00',
    messages: [
      {
        id: 'msg-1',
        sender: 'Mirza Jahangir Khan',
        role: 'School Principal',
        avatar: 'https://images.unsplash.com/photo-1564981797816-1043664bf78d?w=120&auto=format&fit=crop&q=80',
        text: 'Our Board of Governors meeting is scheduled for August 25 to approve the annual TaleemLM Professional subscription invoice. Could you kindly extend our active trial until August 30?',
        timestamp: '2026-08-14 08:00'
      }
    ],
    internalNotes: [
      {
        id: 'note-1',
        author: 'Omer Farooq (Sales)',
        text: 'High potential client in Quetta region. Recommending approval for 14-day extension with Professional plan demo upgrade.',
        date: '2026-08-14 08:15'
      }
    ]
  }
];

export const initialTeamMembers: SuperAdminTeamMember[] = [
  {
    id: 'tm-01',
    name: 'Syed Hamza Ali',
    email: 'hamza.ali@taleemlms.com.pk',
    phone: '+92 300 8594120',
    role: 'Super Admin',
    department: 'Executive',
    permissions: ['all_access', 'tenant_delete', 'financial_override', 'security_policy', 'database_manage'],
    status: 'Active',
    lastLogin: 'Today at 09:42 AM PKT',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80'
  },
  {
    id: 'tm-02',
    name: 'Zainab Fatima',
    email: 'zainab.f@taleemlms.com.pk',
    phone: '+92 321 4455990',
    role: 'Finance Admin',
    department: 'Finance',
    permissions: ['view_revenue', 'manage_invoices', 'process_refunds', '1link_settlements', 'view_schools'],
    status: 'Active',
    lastLogin: 'Today at 08:30 AM PKT',
    avatar: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=120&auto=format&fit=crop&q=80'
  },
  {
    id: 'tm-03',
    name: 'Bilal Hassan Qureshi',
    email: 'bilal.q@taleemlms.com.pk',
    phone: '+92 333 5566778',
    role: 'Support Agent',
    department: 'Customer Support',
    permissions: ['view_tickets', 'reply_tickets', 'assign_tickets', 'view_schools', 'view_users'],
    status: 'Active',
    lastLogin: 'Today at 09:15 AM PKT',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=120&auto=format&fit=crop&q=80'
  },
  {
    id: 'tm-04',
    name: 'Omer Farooq',
    email: 'omer.f@taleemlms.com.pk',
    phone: '+92 301 9988776',
    role: 'Sales Manager',
    department: 'Sales',
    permissions: ['view_schools', 'create_trials', 'view_leads', 'apply_discounts', 'extend_trials'],
    status: 'Active',
    lastLogin: 'Yesterday at 05:20 PM PKT',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=120&auto=format&fit=crop&q=80'
  },
  {
    id: 'tm-05',
    name: 'Kashif Mehmood',
    email: 'kashif.m@taleemlms.com.pk',
    phone: '+92 345 1122334',
    role: 'Technical Admin',
    department: 'Engineering',
    permissions: ['system_health', 'audit_logs', 'redis_queues', 'sms_gateways', 'database_backups'],
    status: 'Active',
    lastLogin: 'Today at 07:05 AM PKT',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80'
  },
  {
    id: 'tm-06',
    name: 'Maryam Nawazish',
    email: 'maryam.n@taleemlms.com.pk',
    phone: '+92 322 8877665',
    role: 'Read-only Analyst',
    department: 'Operations',
    permissions: ['view_analytics', 'view_schools', 'view_reports', 'read_only_access'],
    status: 'Active',
    lastLogin: 'Aug 12 at 04:10 PM PKT',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=120&auto=format&fit=crop&q=80'
  }
];

export const initialAuditLogs: AuditLog[] = [
  {
    id: 'log-8891',
    timestamp: '2026-08-14 09:30:15 PKT',
    actor: 'Syed Hamza Ali',
    adminName: 'Syed Hamza Ali',
    adminEmail: 'hamza.ali@taleemlms.com.pk',
    adminRole: 'Super Admin',
    action: 'User Impersonation',
    target: 'Dr. Tariq Mahmood Malik (Principal)',
    category: 'Security',
    schoolName: 'Beaconhouse School System (Main Campus)',
    ipAddress: '110.39.28.14 (Lahore, PK)',
    location: 'Lahore, Pakistan',
    severity: 'warning',
    details: 'Impersonated school principal to verify Cambridge A-Level Grade Card report generator template.',
    result: 'Success'
  },
  {
    id: 'log-8890',
    timestamp: '2026-08-14 08:45:00 PKT',
    actor: 'Zainab Fatima',
    adminName: 'Zainab Fatima',
    adminEmail: 'zainab.f@taleemlms.com.pk',
    adminRole: 'Finance Admin',
    action: 'Payment Refunded',
    target: 'INV-SaaS-2026-0899 (PKR 15,000)',
    category: 'Billing',
    schoolName: 'Roots Millennium Colleges (Kingsbury Campus)',
    ipAddress: '39.40.182.91 (Islamabad, PK)',
    location: 'Islamabad, Pakistan',
    severity: 'danger',
    details: 'Issued mid-cycle downgrade refund via Meezan Direct Bank Transfer.',
    result: 'Success'
  },
  {
    id: 'log-8889',
    timestamp: '2026-08-13 16:12:33 PKT',
    actor: 'Omer Farooq',
    adminName: 'Omer Farooq',
    adminEmail: 'omer.f@taleemlms.com.pk',
    adminRole: 'Sales Manager',
    action: 'Subscription Changed',
    target: 'Quetta Model Academy (Extended 14 Days)',
    category: 'Subscription',
    schoolName: 'Quetta Model Academy & College',
    ipAddress: '182.185.120.4 (Karachi, PK)',
    location: 'Karachi, Pakistan',
    severity: 'info',
    details: 'Extended active trial to 2026-08-30 pending Board meeting.',
    result: 'Success'
  },
  {
    id: 'log-8888',
    timestamp: '2026-08-12 11:20:10 PKT',
    actor: 'Syed Hamza Ali',
    adminName: 'Syed Hamza Ali',
    adminEmail: 'hamza.ali@taleemlms.com.pk',
    adminRole: 'Super Admin',
    action: 'School Suspended',
    target: 'Crescent Model Higher Secondary School',
    category: 'Tenant Management',
    schoolName: 'Crescent Model Higher Secondary School',
    ipAddress: '110.39.28.14 (Lahore, PK)',
    location: 'Lahore, Pakistan',
    severity: 'danger',
    details: 'Suspended school portal access after 3 consecutive failed monthly billing payment cycles.',
    result: 'Success'
  },
  {
    id: 'log-8887',
    timestamp: '2026-08-11 15:40:02 PKT',
    actor: 'Kashif Mehmood',
    adminName: 'Kashif Mehmood',
    adminEmail: 'kashif.m@taleemlms.com.pk',
    adminRole: 'Technical Admin',
    action: 'Announcement Broadcast',
    target: 'All 1,284 Educational Institutions',
    category: 'System',
    schoolName: 'Nationwide Broadcast',
    ipAddress: '110.39.28.14 (Lahore, PK)',
    location: 'Lahore, Pakistan',
    severity: 'info',
    details: 'Sent system maintenance notification regarding scheduled SBP 1Link banking upgrade.',
    result: 'Success'
  }
];

export const initialSystemServices: SystemServiceStatus[] = [
  {
    name: 'Primary SaaS Core API Gateway',
    category: 'Core API',
    status: 'Operational',
    uptimePct: 99.99,
    latencyMs: 38,
    lastChecked: '30s ago',
    description: 'Multi-tenant Node.js + Express API cluster hosted in Pakistan Region'
  },
  {
    name: 'PostgreSQL Multi-Tenant Database',
    category: 'Database',
    status: 'Operational',
    uptimePct: 99.98,
    latencyMs: 14,
    lastChecked: '15s ago',
    description: 'Isolated tenant schemas with read replicas in Islamabad & Karachi'
  },
  {
    name: 'Wasabi & Cloudflare R2 Media Storage',
    category: 'Storage',
    status: 'Operational',
    uptimePct: 100.0,
    latencyMs: 45,
    lastChecked: '1m ago',
    description: 'Encrypted document repositories for student records, video lectures & homework files'
  },
  {
    name: 'Redis Queue & Background Workers',
    category: 'Queue',
    status: 'Operational',
    uptimePct: 99.95,
    latencyMs: 8,
    lastChecked: '45s ago',
    description: 'Processing 45,000+ daily student attendance records and report card PDF rendering'
  },
  {
    name: 'Pakistan Telco SMS Gateway (Telenor / Jazz / Zong)',
    category: 'Communication',
    status: 'Operational',
    uptimePct: 99.85,
    latencyMs: 110,
    lastChecked: '2m ago',
    description: 'Branded SMS mask (TALEEM-LMS) delivering 120k daily OTP & fee alert messages'
  },
  {
    name: 'WhatsApp Official Cloud API',
    category: 'Communication',
    status: 'Operational',
    uptimePct: 99.92,
    latencyMs: 95,
    lastChecked: '1m ago',
    description: 'Meta Verified business account sending daily student diary and automated invoices'
  },
  {
    name: '1Link 1Bill & Raast Switch',
    category: 'Payment Gateway',
    status: 'Operational',
    uptimePct: 99.70,
    latencyMs: 180,
    lastChecked: '3m ago',
    description: 'Direct State Bank of Pakistan 1Link utility bill connection for 35+ commercial banks'
  },
  {
    name: 'JazzCash & EasyPaisa Merchant Gateway',
    category: 'Payment Gateway',
    status: 'Operational',
    uptimePct: 99.88,
    latencyMs: 140,
    lastChecked: '1m ago',
    description: 'Mobile wallet instant collection API with automated IPN callback webhooks'
  }
];

export const initialSystemIncidents: SystemIncident[] = [
  {
    id: 'inc-102',
    title: '1Link 1Bill Bank Settlement Webhook Queue Latency',
    status: 'Resolved',
    severity: 'Minor',
    affectedService: '1Link 1Bill & Raast Switch',
    startedAt: '2026-08-12 14:00 PKT',
    resolvedAt: '2026-08-12 16:15 PKT',
    message: 'State Bank 1Link conducted scheduled settlement clearance. All queued fee receipts were re-delivered with 0 dropped webhooks.'
  },
  {
    id: 'inc-101',
    title: 'Telenor Pakistan Bulk SMS Dispatch Delay in North Region',
    status: 'Resolved',
    severity: 'Minor',
    affectedService: 'Pakistan Telco SMS Gateway',
    startedAt: '2026-08-04 08:30 PKT',
    resolvedAt: '2026-08-04 09:45 PKT',
    message: 'Temporary routing fallback activated via Jazz SMS backup gateway. SMS delivery resumed at 99.4% within 12 seconds.'
  }
];

export const initialBroadcastAnnouncements: GlobalAnnouncement[] = [
  {
    id: 'anc-glob-01',
    title: 'Scheduled SBP 1Link Banking Gateway Maintenance Notice',
    content: 'State Bank of Pakistan and 1Link will perform scheduled network optimization on Sunday from 02:00 AM to 05:00 AM PKT. Online fee payments via mobile banking apps may experience brief delays during this window.',
    targetType: 'all_schools',
    type: 'warning',
    channels: ['in_app', 'email'],
    status: 'Sent',
    sentAt: '2026-08-11 15:40 PKT',
    author: 'Syed Hamza Ali (Super Admin)',
    recipientCount: 1284
  },
  {
    id: 'anc-glob-02',
    title: 'New AI Attendance & Federal Board (FBISE) SLO Rubric Module Live!',
    content: 'We are pleased to announce the release of TaleemLM v4.2 with automated Student Learning Outcomes (SLO) question bank generator aligned with Single National Curriculum (SNC) guidelines.',
    targetType: 'plan',
    targetFilterValue: 'Professional, Enterprise',
    type: 'info',
    channels: ['in_app', 'email', 'sms'],
    status: 'Sent',
    sentAt: '2026-08-05 10:00 PKT',
    author: 'Product Management Team',
    recipientCount: 972
  }
];

export const initialSuperAdminSettings: SuperAdminSettingsState = {
  companyName: 'TaleemLM EdTech Private Limited',
  supportEmail: 'support@taleemlms.com.pk',
  supportPhone: '+92 42 111 825 336',
  billingCurrency: 'PKR',
  defaultTrialDays: 14,
  autoInvoicing: true,
  smsGatewayProvider: 'Telenor SMS Pro',
  whatsappApiEnabled: true,
  twoFactorEnforced: true,
  maintenanceMode: false,
  jazzCashMerchantId: 'JC_MERCH_994821',
  easyPaisaStoreId: 'EP_STORE_88319',
  oneLinkBillerCode: '1LINK_BILL_7720',
  stripePublicKey: 'pk_live_51Mxxxxxxxxxxxxxxxxxxx',
  storageProvider: 'Cloudflare R2',
  backupFrequency: 'Daily (03:00 AM PKT)',
  allowSelfRegistration: false
};

// Aliases for compatibility
export const INITIAL_SUPER_ADMIN = initialTeamMembers[0];
export const INITIAL_SCHOOLS = initialSchoolTenants;
export const INITIAL_PLANS = initialSuperAdminPlans;
export const INITIAL_TRANSACTIONS = initialPaymentTransactions;
export const INITIAL_GLOBAL_USERS = initialGlobalUsers;
export const INITIAL_TICKETS = initialSupportTickets;
export const INITIAL_AUDIT_LOGS = initialAuditLogs;
export const INITIAL_SYSTEM_SERVICES = initialSystemServices;
export const INITIAL_SETTINGS = initialSuperAdminSettings;
export const INITIAL_TEAM_MEMBERS = initialTeamMembers;
export const INITIAL_INCIDENTS = initialSystemIncidents;
export const INITIAL_ANNOUNCEMENTS = initialBroadcastAnnouncements;
